#ifndef __TERMIANL_NETSTATE_HPP__
#define __TERMINAL_NETSTATE_HPP__

#include <DataTypes.hpp>

namespace TERMINAL
{
	enum T_CONNECTIONSTATE
	{
		T_CONNECTIONSTATE_CONNECTING = 0,
		T_CONNECTIONSTATE_CONNECTED,
		T_CONNECTIONSTATE_DISCONNECTING,
		T_CONNECTIONSTATE_DISCONNECTED
	};
}

#endif // __TERMINAL_NETSTATE_HPP__

